<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace />
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fx.Core\Fx.Core\Fx.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!--TODO remove this-->
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>OddTrotter.Core.V3.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
